### ISSUE TITLE
extend create-user functionality

### ISSUE THREAD

**Issue by peb-adr** [OpenSlides/openslides-manage-service#130]
The `create-user` command works good so far.
The file mechanism is also nice to use.

But we need to set more options for an initial user then possible with the current version.
Because right now the new user has no permissions, where as the initial user should be the administrator of the organization.
Also login wasn't possible because `is_active` was not set.

So I tested around with curl. The following shows the fields needed to create a user with admin permissions for the orga + default committee + default meeting (using the committee, meeting and group id's defined in [backend/initial-data.json](https://github.com/OpenSlides/openslides-backend/blob/master/global/data/initial-data.json))

```bash
curl localhost:9002/internal/handle_request \
  -X POST -H "Content-Type: application/json" -d '
    {                                                                               
      "action": "user.create",
      "data": [
        {
          "username": "adrian",
          "default_password": "asdf",
          "first_name": "Adrian",
          "last_name": "Richter",
          "email": "adrian@intevation.de",
          "is_active": true,
          "organization_management_level": "can_manage_organization", /* orga permissions */
          "committee_$_management_level": { "1": "can_manage" }, /* committee permissions */
          "group_$_ids": { "1": [ 1, 2 ] } /* participant (1) and admin (2) groups for default meeting (1) */
        }
      ]
    }
  '
````

Though I am not sure how these should be passed.
Obviously the yaml file could look like this:
```yaml
username: adrian
default_password: notweak
first_name: Adrian
last_name: Richter
email: adrian@intevation.de
is_active: true,
organization_management_level: can_manage_organization,
committee_$_management_level: { "1": "can_manage" },
group_$_ids: { "1": [ 1, 2 ] }
```
This would assume that every value is interpreted as raw json.
A downfall is, that this is not intuitively readable.

Another option i had in mind is just having a flag `create-user --admin` which will insert the permission related fields. But this will break when the initial configuration gets changed.

So I think having it explicitly all in the file would be our best bet.
Open for other suggestions though @normanjaeckel and maybe @gsiv
