### ISSUE TITLE
Login not possible with superadmin and init-data times out

### ISSUE THREAD

**Issue by n2o** [OpenSlides/openslides-manage-service#144]
Hello,

I just wanted to install openslides, which is a great tool, for an event for this weekend. But apparently I am not able to login with `superadmin` as usernamen and password and also the `init-data`-step times out, which is why I am not quite sure, if everything went fine.

I followed your installation instructions, generated a docker-compose.yml file and started it. When I want to login, I try with superadmin and receive the following error message:

```
auth_1             | [12.01.2022 -- 22:25:07]: http://my.host: POST -- /system/auth/login/ 
auth_1             | [12.01.2022 -- 22:25:07]: user: superadmin -- signs in 
datastoreReader_1  | [2022-01-12 22:25:07 +0000] [20] [INFO] FILTER-request: {'collection': 'user', 'filter': {'field': 'username', 'value': 'superadmin', 'operator': '='}, 'mapped_fields': ['username', 'password', 'id', 'is_active', 'meta_deleted']}
auth_1             | Stacktrace:
auth_1             |  AuthenticationException [Error]: Username or password is incorrect.
auth_1             |     at new AuthenticationException (/app/core/exceptions/authentication-exception.js:7:9)
auth_1             |     at UserService.<anonymous> (/app/api/services/user-service.js:41:23)
auth_1             |     at Generator.next (<anonymous>)
auth_1             |     at fulfilled (/app/node_modules/tslib/tslib.js:114:62)
auth_1             |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
auth_1             |   statusCode: 403,
auth_1             |   title: 'Username or password is incorrect.'
auth_1             | }
```

My docker-compose.yml looks like this (I did not change a lot, just configured letsencrypt and træfik):

```yml
---
version: "3.7"

x-default-environment:
  &default-environment
  ACTION_HOST: backend
  ACTION_PORT: "9002"
  AUTH_HOST: auth
  AUTH_PORT: "9004"
  AUTOUPDATE_HOST: autoupdate
  AUTOUPDATE_PORT: "9012"
  CACHE_HOST: redis
  CACHE_PORT: "6379"
  DATASTORE_DATABASE_HOST: postgres
  DATASTORE_DATABASE_NAME: openslides
  DATASTORE_DATABASE_PASSWORD_FILE: /run/secrets/postgres_password
  DATASTORE_DATABASE_PORT: "5432"
  DATASTORE_DATABASE_USER: openslides
  DATASTORE_READER_HOST: datastoreReader
  DATASTORE_READER_PORT: "9010"
  DATASTORE_WRITER_HOST: datastoreWriter
  DATASTORE_WRITER_PORT: "9011"
  ICC_HOST: icc
  ICC_PORT: "9007"
  ICC_REDIS_HOST: redis
  ICC_REDIS_PORT: "6379"
  INTERNAL_AUTH_PASSWORD_FILE: /run/secrets/internal_auth_password
  MANAGE_ACTION_HOST: backendManage
  MANAGE_AUTH_PASSWORD_FILE: /run/secrets/manage_auth_password
  MANAGE_HOST: manage
  MANAGE_PORT: "9008"
  MEDIA_BLOCK_SIZE: "4096"
  MEDIA_DATABASE_HOST: postgres
  MEDIA_DATABASE_NAME: openslides
  MEDIA_DATABASE_PASSWORD_FILE: /run/secrets/postgres_password
  MEDIA_DATABASE_PORT: "5432"
  MEDIA_DATABASE_USER: openslides
  MEDIA_HOST: media
  MEDIA_PORT: "9006"
  MEDIA_PRESENTER_HOST: backend
  MEDIA_PRESENTER_PORT: "9003"
  MESSAGE_BUS_HOST: redis
  MESSAGE_BUS_PORT: "6379"
  OPENSLIDES_DEVELOPMENT: "false"
  PRESENTER_HOST: backend
  PRESENTER_PORT: "9003"
  VOTE_DATABASE_HOST: postgres
  VOTE_DATABASE_NAME: openslides
  VOTE_DATABASE_PASSWORD_FILE: /run/secrets/postgres_password
  VOTE_DATABASE_PORT: "5432"
  VOTE_DATABASE_USER: openslides
  VOTE_HOST: vote
  VOTE_PORT: "9013"
  VOTE_REDIS_HOST: redis
  VOTE_REDIS_PORT: "6379"

services:
  proxy:
    image: ghcr.io/openslides/openslides/openslides-proxy:latest
    depends_on:
      - client
      - backend
      - autoupdate
      - auth
      - media
      - icc
    environment:
      <<: *default-environment
      # ENABLE_LOCAL_HTTPS: 0
      # HTTPS_CERT_FILE: /run/secrets/cert_crt
      # HTTPS_KEY_FILE: /run/secrets/cert_key
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:my.host"
      - "traefik.port=8000"
      - "traefik.docker.network=web"
    networks:
      - uplink
      - frontend
      - web
    # ports:
    #   - 127.0.0.1:8000:8000
    secrets:
      - cert_crt
      - cert_key

  client:
    image: ghcr.io/openslides/openslides/openslides-client:latest
    depends_on:
      - backend
      - autoupdate
      - auth
      - media
      - icc
    labels:
      - "traefik.enable=false"
    environment:
      <<: *default-environment
    networks:
      - frontend

  backend:
    image: ghcr.io/openslides/openslides/openslides-backend:latest
    depends_on:
      - datastoreWriter
      - auth
      - postgres
    labels:
      - "traefik.enable=false"
    environment:
      <<: *default-environment
    networks:
      - frontend
      - data
    secrets:
      - auth_token_key
      - auth_cookie_key
      - postgres_password

  backendManage:
    image: ghcr.io/openslides/openslides/openslides-backend:latest
    depends_on:
      - datastoreWriter
      - postgres
    labels:
      - "traefik.enable=false"
    environment:
      <<: *default-environment
    networks:
      - data
    secrets:
      - auth_token_key
      - auth_cookie_key
      - internal_auth_password
      - postgres_password

  datastoreReader:
    image: ghcr.io/openslides/openslides/openslides-datastore-reader:latest
    depends_on:
      - postgres
    labels:
      - "traefik.enable=false"
    environment:
      <<: *default-environment
      NUM_WORKERS: "8"
    networks:
      - data
    secrets:
      - postgres_password

  datastoreWriter:
    image: ghcr.io/openslides/openslides/openslides-datastore-writer:latest
    depends_on:
      - postgres
      - redis
    labels:
      - "traefik.enable=false"
    environment:
      <<: *default-environment
    networks:
      - data
    secrets:
      - postgres_password

  postgres:
    image: postgres:11
    environment:
      <<: *default-environment
      POSTGRES_DB: openslides
      POSTGRES_USER: openslides
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      PGDATA: /var/lib/postgresql/data/pgdata
    labels:
      - "traefik.enable=false"
    networks:
      - data
    secrets:
      - postgres_password
    volumes:
      - ./db-data:/var/lib/postgresql/data

  autoupdate:
    image: ghcr.io/openslides/openslides/openslides-autoupdate:latest
    depends_on:
      - datastoreReader
      - redis
    environment:
      <<: *default-environment
      MESSAGING: redis
      AUTH: ticket
    labels:
      - "traefik.enable=false"
    networks:
      - frontend
      - data
    secrets:
      - auth_token_key
      - auth_cookie_key

  auth:
    image: ghcr.io/openslides/openslides/openslides-auth:latest
    depends_on:
      - datastoreReader
      - redis
    environment:
      <<: *default-environment
    networks:
      - frontend
      - data
    labels:
      - "traefik.enable=false"
    secrets:
      - auth_token_key
      - auth_cookie_key

  vote:
    image: ghcr.io/openslides/openslides/openslides-vote:latest
    depends_on:
      - backend
      - datastoreReader
      - auth
      - autoupdate
      - redis
    environment:
      <<: *default-environment
      MESSAGING: redis
      AUTH: ticket
    labels:
      - "traefik.enable=false"
    networks:
      - frontend
      - data
    secrets:
      - auth_token_key
      - auth_cookie_key
      - postgres_password

  redis:
    image: redis:latest
    command: redis-server --save ""
    environment:
      <<: *default-environment
    labels:
      - "traefik.enable=false"
    networks:
      - data

  media:
    image: ghcr.io/openslides/openslides/openslides-media:latest
    depends_on:
      - backend
      - postgres
    environment:
      <<: *default-environment
    labels:
      - "traefik.enable=false"
    networks:
      - frontend
      - data
    secrets:
      - postgres_password

  icc:
    image: ghcr.io/openslides/openslides/openslides-icc:latest
    depends_on:
      - datastoreReader
      - postgres
      - redis
    environment:
      <<: *default-environment
      MESSAGING: redis
      AUTH: ticket
    labels:
      - "traefik.enable=false"
    networks:
      - frontend
      - data
    secrets:
      - auth_token_key
      - auth_cookie_key

  manage:
    image: ghcr.io/openslides/openslides/openslides-manage:latest
    depends_on:
      - datastoreReader
      - datastoreWriter
      - auth
      - backendManage
    environment:
      <<: *default-environment
    labels:
      - "traefik.enable=false"
    networks:
      - frontend
      - data
    secrets:
      - superadmin
      - manage_auth_password
      - internal_auth_password

networks:
  uplink: null
  frontend:
    internal: true
  data:
    internal: true
  web:
    external: true

secrets:
  auth_token_key:
    file: ./secrets/auth_token_key
  auth_cookie_key:
    file: ./secrets/auth_cookie_key
  superadmin:
    file: ./secrets/superadmin
  manage_auth_password:
    file: ./secrets/manage_auth_password
  internal_auth_password:
    file: ./secrets/internal_auth_password
  postgres_password:
    file: ./secrets/postgres_password
  cert_crt:
    file: ./secrets/cert_crt
  cert_key:
    file: ./secrets/cert_key
```

When I try to use `init-data`, I get this error message: `Error: connecting to gRPC server: creating gRPC client connection with grpc.DialContext(): context deadline exceeded`

The docker-compose file looks like this:

```bash
Attaching to openslides_postgres_1, openslides_redis_1
redis_1            | 1:C 12 Jan 2022 22:22:09.683 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1            | 1:C 12 Jan 2022 22:22:09.683 # Redis version=6.2.6, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1            | 1:C 12 Jan 2022 22:22:09.683 # Configuration loaded
redis_1            | 1:M 12 Jan 2022 22:22:09.684 * monotonic clock: POSIX clock_gettime
redis_1            | 1:M 12 Jan 2022 22:22:09.685 * Running mode=standalone, port=6379.
redis_1            | 1:M 12 Jan 2022 22:22:09.685 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1            | 1:M 12 Jan 2022 22:22:09.685 # Server initialized
redis_1            | 1:M 12 Jan 2022 22:22:09.685 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
redis_1            | 1:M 12 Jan 2022 22:22:09.685 * Ready to accept connections
postgres_1         | The files belonging to this database system will be owned by user "postgres".
postgres_1         | This user must also own the server process.
postgres_1         | 
postgres_1         | The database cluster will be initialized with locale "en_US.utf8".
postgres_1         | The default database encoding has accordingly been set to "UTF8".
postgres_1         | The default text search configuration will be set to "english".
postgres_1         | 
postgres_1         | Data page checksums are disabled.
postgres_1         | 
postgres_1         | fixing permissions on existing directory /var/lib/postgresql/data/pgdata ... ok
postgres_1         | creating subdirectories ... ok
postgres_1         | selecting default max_connections ... 100
postgres_1         | selecting default shared_buffers ... 128MB
postgres_1         | selecting default timezone ... Etc/UTC
postgres_1         | selecting dynamic shared memory implementation ... posix
postgres_1         | creating configuration files ... ok
postgres_1         | running bootstrap script ... ok
postgres_1         | performing post-bootstrap initialization ... ok
postgres_1         | 
postgres_1         | WARNING: enabling "trust" authentication for local connections
postgres_1         | You can change this by editing pg_hba.conf or using the option -A, or
postgres_1         | --auth-local and --auth-host, the next time you run initdb.
postgres_1         | syncing data to disk ... ok
postgres_1         | 
postgres_1         | Success. You can now start the database server using:
postgres_1         | 
postgres_1         |     pg_ctl -D /var/lib/postgresql/data/pgdata -l logfile start
postgres_1         | 
postgres_1         | waiting for server to start....2022-01-12 22:22:14.267 UTC [49] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
datastoreReader_1  | postgres:5432 - no response
datastoreReader_1  | Waiting for Postgres server 'postgres' to become available...
postgres_1         | 2022-01-12 22:22:14.749 UTC [50] LOG:  database system was shut down at 2022-01-12 22:22:10 UTC
datastoreWriter_1  | wait-for-it: waiting for redis:6379 without a timeout
datastoreWriter_1  | wait-for-it: redis:6379 is available after 0 seconds
datastoreWriter_1  | postgres:5432 - no response
datastoreWriter_1  | Waiting for Postgres server 'postgres' to become available...
postgres_1         | 2022-01-12 22:22:14.922 UTC [49] LOG:  database system is ready to accept connections
postgres_1         |  done
postgres_1         | server started
datastoreReader_1  | postgres:5432 - no response
datastoreReader_1  | Waiting for Postgres server 'postgres' to become available...
datastoreWriter_1  | postgres:5432 - no response
datastoreWriter_1  | Waiting for Postgres server 'postgres' to become available...
postgres_1         | CREATE DATABASE
postgres_1         | 
postgres_1         | 
postgres_1         | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
postgres_1         | 
postgres_1         | 2022-01-12 22:22:18.112 UTC [49] LOG:  received fast shutdown request
postgres_1         | waiting for server to shut down....2022-01-12 22:22:18.258 UTC [49] LOG:  aborting any active transactions
postgres_1         | 2022-01-12 22:22:18.263 UTC [49] LOG:  background worker "logical replication launcher" (PID 56) exited with exit code 1
postgres_1         | 2022-01-12 22:22:18.267 UTC [51] LOG:  shutting down
postgres_1         | .2022-01-12 22:22:19.926 UTC [49] LOG:  database system is shut down
postgres_1         |  done
postgres_1         | server stopped
postgres_1         | 
postgres_1         | PostgreSQL init process complete; ready for start up.
postgres_1         | 
postgres_1         | 2022-01-12 22:22:20.173 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres_1         | 2022-01-12 22:22:20.173 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres_1         | 2022-01-12 22:22:20.398 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
auth_1             | redis:6379 is available
auth_1             | redis:6379 is available
auth_1             | [12.01.2022 -- 22:22:20]: Database: redis:6379 
auth_1             | [12.01.2022 -- 22:22:20]: Database: redis:6379 
auth_1             | [12.01.2022 -- 22:22:20]: Message bus: redis:6379 
auth_1             | This server is listen on port 9004.
postgres_1         | 2022-01-12 22:22:20.911 UTC [77] LOG:  database system was shut down at 2022-01-12 22:22:19 UTC
datastoreWriter_1  | postgres:5432 - rejecting connections
datastoreWriter_1  | Waiting for Postgres server 'postgres' to become available...
datastoreReader_1  | postgres:5432 - rejecting connections
datastoreReader_1  | Waiting for Postgres server 'postgres' to become available...
postgres_1         | 2022-01-12 22:22:20.913 UTC [79] FATAL:  the database system is starting up
postgres_1         | 2022-01-12 22:22:20.913 UTC [78] FATAL:  the database system is starting up
postgres_1         | 2022-01-12 22:22:21.123 UTC [1] LOG:  database system is ready to accept connections
backendManage_1    | waiting for datastoreWriter:9011
backendManage_1    | waiting for datastoreWriter:9011
icc_1              | 2022/01/12 22:22:22 Messaging Service: redis
icc_1              | 2022/01/12 22:22:22 Auth Method: ticket
icc_1              | 2022/01/12 22:22:22 Auth Service: http://auth:9004
icc_1              | 2022/01/12 22:22:22 Listen on :9007
backendManage_1    | waiting for datastoreWriter:9011
autoupdate_1       | Messaging Service: redis
autoupdate_1       | Auth Method: ticket
autoupdate_1       | Auth Service: http://auth:9004
autoupdate_1       | Listen on :9012
datastoreReader_1  | postgres:5432 - accepting connections
datastoreWriter_1  | postgres:5432 - accepting connections
datastoreWriter_1  | DO
backendManage_1    | waiting for datastoreWriter:9011
datastoreReader_1  | [2022-01-12 22:22:24 +0000] [14] [INFO] Starting gunicorn 20.1.0
datastoreReader_1  | [2022-01-12 22:22:24 +0000] [14] [INFO] Listening at: http://0.0.0.0:9010 (14)
datastoreReader_1  | [2022-01-12 22:22:24 +0000] [14] [INFO] Using worker: sync
datastoreReader_1  | [2022-01-12 22:22:24 +0000] [16] [INFO] Booting worker with pid: 16
datastoreReader_1  | [2022-01-12 22:22:24 +0000] [17] [INFO] Booting worker with pid: 17
datastoreReader_1  | [2022-01-12 22:22:24 +0000] [18] [INFO] Booting worker with pid: 18
datastoreReader_1  | [2022-01-12 22:22:24 +0000] [19] [INFO] Booting worker with pid: 19
datastoreWriter_1  | CREATE TABLE
datastoreReader_1  | [2022-01-12 22:22:24 +0000] [20] [INFO] Booting worker with pid: 20
datastoreReader_1  | [2022-01-12 22:22:24 +0000] [21] [INFO] Booting worker with pid: 21
datastoreReader_1  | [2022-01-12 22:22:24 +0000] [22] [INFO] Booting worker with pid: 22
datastoreReader_1  | [2022-01-12 22:22:24 +0000] [23] [INFO] Booting worker with pid: 23
datastoreWriter_1  | CREATE TABLE
datastoreWriter_1  | CREATE INDEX
backendManage_1    | waiting for datastoreWriter:9011
datastoreWriter_1  | CREATE TABLE
datastoreWriter_1  | CREATE TABLE
datastoreWriter_1  | CREATE INDEX
datastoreWriter_1  | CREATE TABLE
datastoreWriter_1  | CREATE TABLE
datastoreWriter_1  | CREATE TABLE
datastoreWriter_1  | CREATE INDEX
backendManage_1    | waiting for datastoreWriter:9011
datastoreWriter_1  | CREATE TABLE
backend_1          | waiting for datastoreWriter:9011
datastoreWriter_1  | CREATE INDEX
manage_1           | 2022/01/12 22:22:26 Running manage service on :9008
datastoreWriter_1  | CREATE TABLE
datastoreWriter_1  | CREATE TABLE
backend_1          | waiting for datastoreWriter:9011
backendManage_1    | waiting for datastoreWriter:9011
datastoreWriter_1  | [2022-01-12 22:22:27 +0000] [30] [INFO] Starting gunicorn 20.1.0
datastoreWriter_1  | [2022-01-12 22:22:27 +0000] [30] [INFO] Listening at: http://0.0.0.0:9011 (30)
datastoreWriter_1  | [2022-01-12 22:22:27 +0000] [30] [INFO] Using worker: sync
datastoreWriter_1  | [2022-01-12 22:22:27 +0000] [32] [INFO] Booting worker with pid: 32
backend_1          | datastoreWriter:9011 is available
backendManage_1    | datastoreWriter:9011 is available
backend_1          | Start all components in child processes. Parent process id is 1.
backendManage_1    | Start all components in child processes. Parent process id is 1.
backendManage_1    | [2022-01-12 22:22:28 +0000] [24] [INFO] Starting gunicorn 20.1.0
backendManage_1    | [2022-01-12 22:22:28 +0000] [24] [INFO] Listening at: http://0.0.0.0:9002 (24)
backendManage_1    | [2022-01-12 22:22:28 +0000] [24] [INFO] Using worker: sync
backendManage_1    | [2022-01-12 22:22:28 +0000] [25] [INFO] Starting gunicorn 20.1.0
backendManage_1    | [2022-01-12 22:22:28 +0000] [25] [INFO] Listening at: http://0.0.0.0:9003 (25)
backendManage_1    | [2022-01-12 22:22:28 +0000] [25] [INFO] Using worker: sync
backendManage_1    | [2022-01-12 22:22:28 +0000] [26] [INFO] Booting worker with pid: 26
backend_1          | [2022-01-12 22:22:28 +0000] [14] [INFO] Starting gunicorn 20.1.0
backend_1          | [2022-01-12 22:22:28 +0000] [14] [INFO] Listening at: http://0.0.0.0:9002 (14)
backend_1          | [2022-01-12 22:22:28 +0000] [14] [INFO] Using worker: sync
backendManage_1    | [2022-01-12 22:22:28 +0000] [27] [INFO] Booting worker with pid: 27
backend_1          | [2022-01-12 22:22:29 +0000] [15] [INFO] Starting gunicorn 20.1.0
backend_1          | [2022-01-12 22:22:29 +0000] [15] [INFO] Listening at: http://0.0.0.0:9003 (15)
backend_1          | [2022-01-12 22:22:29 +0000] [15] [INFO] Using worker: sync
backend_1          | [2022-01-12 22:22:29 +0000] [16] [INFO] Booting worker with pid: 16
backend_1          | [2022-01-12 22:22:29 +0000] [17] [INFO] Booting worker with pid: 17
postgres_1         | 2022-01-12 22:22:31.103 UTC [89] FATAL:  password authentication failed for user "root"
postgres_1         | 2022-01-12 22:22:31.103 UTC [89] DETAIL:  Role "root" does not exist.
postgres_1         |    Connection matched pg_hba.conf line 95: "host all all all md5"
media_1            | postgres:5432 - accepting connections
media_1            | CREATE SCHEMA
media_1            | CREATE TABLE
vote_1             | 2022/01/12 22:22:31 Messaging Service: redis
vote_1             | Auth Method: ticket
vote_1             | Auth Service: http://auth:9004
media_1            | CREATE TABLE
vote_1             | 2022/01/12 22:22:31 Listen on :9013
media_1            | [2022-01-12 22:22:32 +0000] [1] [INFO] Starting gunicorn 20.1.0
media_1            | [2022-01-12 22:22:32 +0000] [1] [INFO] Listening at: http://0.0.0.0:9006 (1)
media_1            | [2022-01-12 22:22:32 +0000] [1] [INFO] Using worker: sync
media_1            | [2022-01-12 22:22:32 +0000] [17] [INFO] Booting worker with pid: 17
media_1            | [2022-01-12 22:22:32 +0000] [17] [INFO] Started Media-Server
client_1           | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
client_1           | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
client_1           | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
client_1           | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
client_1           | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
client_1           | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
client_1           | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
client_1           | /docker-entrypoint.sh: Configuration complete; ready for start up
proxy_1            | {"level":"info","ts":1642026158.7199588,"msg":"using provided configuration","config_file":"/etc/caddy/config.json","config_adapter":""}
proxy_1            | {"level":"info","ts":1642026158.721949,"logger":"admin","msg":"admin endpoint started","address":"tcp/localhost:2019","enforce_origin":false,"origins":["[::1]:2019","127.0.0.1:2019","localhost:2019"]}
proxy_1            | {"level":"info","ts":1642026158.7244635,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc000387ea0"}
proxy_1            | {"level":"info","ts":1642026158.7266212,"msg":"autosaved config","file":"/config/caddy/autosave.json"}
proxy_1            | {"level":"info","ts":1642026158.726639,"msg":"serving initial configuration"}
proxy_1            | {"level":"info","ts":1642026158.726608,"logger":"tls","msg":"cleaned up storage units"}
auth_1             | [12.01.2022 -- 22:23:20]: http://my.host: POST -- /system/auth/login/ 
auth_1             | [12.01.2022 -- 22:23:20]: user: superadmin -- signs in 
datastoreReader_1  | [2022-01-12 22:23:20 +0000] [22] [INFO] FILTER-request: {'collection': 'user', 'filter': {'field': 'username', 'value': 'superadmin', 'operator': '='}, 'mapped_fields': ['username', 'password', 'id', 'is_active', 'meta_deleted']}
auth_1             | Stacktrace:
auth_1             |  AuthenticationException [Error]: Username or password is incorrect.
auth_1             |     at new AuthenticationException (/app/core/exceptions/authentication-exception.js:7:9)
auth_1             |     at UserService.<anonymous> (/app/api/services/user-service.js:41:23)
auth_1             |     at Generator.next (<anonymous>)
auth_1             |     at fulfilled (/app/node_modules/tslib/tslib.js:114:62)
auth_1             |     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
auth_1             |   statusCode: 403,
auth_1             |   title: 'Username or password is incorrect.'
auth_1             | }
```

Do you have any ideas on this?

Thanks and best regards :-)
