### ISSUE TITLE
Can't connect to service after installation when using reverse proxy 

### ISSUE THREAD

**Issue by ianhyzy** [OpenSlides/openslides-manage-service#163]
I'm trying to install openslides behind an exisitng NGINX proxy with Let's Encrypt for HTTPS. It wasn't clear to me exactly how to turn off self-signed SSL but after trying the below in docker-compose it seemed to work:

```
services:
  proxy:
    image: ghcr.io/openslides/openslides/openslides-proxy:latest
    depends_on:
      - client
      - backend
      - autoupdate
      - auth
      - media
      - icc
    environment:
      << : *default-environment
      ENABLE_LOCAL_HTTPS: 0
```
(Changing this to false as the docs mention throws an error?)
I also changed system_url to openslides.mydomain.com.

My NGINX config looks like this:
```
server {
        listen                  443 ssl http2;
        listen                  [::]:443 ssl http2;
        server_name             openslides.mydomain.com;

        location / {
                proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header        Host $http_host;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
                proxy_http_version      1.1;
                proxy_buffering         off;
                proxy_read_timeout      20m;
                proxy_pass              http://192.168.1.250;
        }
    ssl_certificate /etc/letsencrypt/live/.../fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/..../privkey.pem; # managed by Certbot

}
```

However, after running the service, I can't connect via opensldies.mydomain.com (502 Bad Gateway) or with http://192.168.1.250:9000 (ERR_CONNECTION_REFUSED) to finish set up. Any idea what I'm doing wrong? Both boxes are Ubuntu 20.04.
