### ISSUE TITLE
expose port 80 in docker-compose.yml when enableAutoHTTPS is true

### ISSUE THREAD

**Issue by b2daniel** [OpenSlides/openslides-manage-service#248]
**Describe the bug**
enableAutoHTTPS fails to get certificates as port 80 is not exposed for verification requests

**How to Reproduce**
1. set up Openslides Instance
2. configure enableAutoHTTPS: true in myconfig.yml
3.  ./openslides config . -c myconfig.yml

=> Port 80 is not exposed in proxy container

also adding:
```
          services:
            proxy:
              environment:
                EXTERNAL_ADDRESS: {{ domain }}
                # Use letsencrypt staging environment for testing
                # ACME_ENDPOINT: https://acme-staging-v02.api.letsencrypt.org/directory
              ports:
                - 0.0.0.0:80:8001
```
to myconfig.yml does not add port 80 to docker-compose.yml

also tried to configure in myconfig:
```
          services:
            proxy:
              environment:
                EXTERNAL_ADDRESS: {{ domain }}
                # Use letsencrypt staging environment for testing
                # ACME_ENDPOINT: https://acme-staging-v02.api.letsencrypt.org/directory
              AdditionalContent
                ports:
                  - 0.0.0.0:80:8001
```
this adds "ports:" a second time instead of adding port 80 under the existing ports node

**Expected behavior**
we can build a running LetsEncrypt Auto-Cert-Config docker-compose.yml by creation of a proper custom config file instead of manually patching docker-compose.yml after every update ;-)

**System information**

- OpenSlides version: [4.2]
