### ISSUE TITLE
Merge custom config files

### ISSUE THREAD

**Issue by normanjaeckel** [OpenSlides/openslides-manage-service#249]
The tool allows the user to provide [multiple config](https://github.com/OpenSlides/openslides-manage-service/blob/main/pkg/config/config.go#L87) files with the `--config` flag.

At the moment we use [mergo](https://github.com/darccio/mergo) to merge all these config files together with the [default configuration](https://github.com/OpenSlides/openslides-manage-service/blob/main/pkg/config/default-config.yml). This library merges the [respective structs](https://github.com/OpenSlides/openslides-manage-service/blob/main/pkg/config/config.go#L165) recursively.

Unfortunately `mergo` does not support merging the values of a map, that are itself a struct, as we do it with the [services map](https://github.com/OpenSlides/openslides-manage-service/blob/main/pkg/config/config.go#L183). This produces wrong output if we have config files with different settings.

E. g. merging
```yaml
services:
  backendAction:
    tag:  foo
```
and
```yaml
services:
   backendAction:
      containerRegistry: bar
```
should provide
```yaml
services:
   backendAction:
      tag: foo
      containerRegistry: bar
```
but it doesn't.

One solution might be that we drop `mergo` and do it by hand, as discussed with @ostcar.
