### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by tanjix** [OpenSlides/openslides-manage-service#68]
Hi Guys!

Following the README instructions by doing:

`$ ./openslides setup .`

and then

`$ docker-compose up --detach`

this throws the following errors:

```
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for x-default-environment: 'PRESENTER_HOST'
Unsupported config option for secrets: 'auth_token_key'
Unsupported config option for networks: 'postgres'
Unsupported config option for services: 'postgres'
root@os4:~/openslides_08092021#
```

How can I fix it? Thanks!

**Comment by normanjaeckel** [comment]
Can you please post your docker-compose version and also the generated docker-compose.yml file?

**Comment by tanjix** [comment]
Hi! Sure!

**docker-compose version:**

```
root@os4:~# docker-compose version
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.9.2
OpenSSL version: OpenSSL 1.1.1k  25 Mar 2021
root@os4:~#
```

**docker-compose.yml:** (got created after running the "./openslides setup ." command)

```
root@os4:~/openslides_08092021# cat docker-compose.yml
---
x-default-environment: &default-environment
  ACTION_HOST: backend
  ACTION_PORT: 9002
  PRESENTER_HOST: backend
  PRESENTER_PORT: 9003

  DATASTORE_READER_HOST: datastore-reader
  DATASTORE_READER_PORT: 9010
  DATASTORE_WRITER_HOST: datastore-writer
  DATASTORE_WRITER_PORT: 9011
  DATASTORE_DATABASE_HOST: postgres
  DATASTORE_DATABASE_PORT: 5432
  DATASTORE_DATABASE_NAME: openslides
  DATASTORE_DATABASE_USER: openslides
  DATASTORE_DATABASE_PASSWORD: openslides

  AUTOUPDATE_HOST: autoupdate
  AUTOUPDATE_PORT: 9012

  AUTH_HOST: auth
  AUTH_PORT: 9004

  CACHE_HOST: redis
  CACHE_PORT: 6379

  MESSAGE_BUS_HOST: redis
  MESSAGE_BUS_PORT: 6379

  MEDIA_HOST: media
  MEDIA_PORT: 9006
  MEDIA_DATABASE_HOST: postgres
  MEDIA_DATABASE_NAME: openslides

  ICC_HOST: icc
  ICC_PORT: 9013
  ICC_REDIS_HOST: redis
  ICC_REDIS_PORT: 6379

  MANAGE_HOST: manage
  MANAGE_PORT: 9008

services:
  proxy:
    image: ghcr.io/openslides/openslides/openslides-proxy:4.0.0-dev
    depends_on:
      - client
      - backend
      - autoupdate
      - auth
      - media
      - icc
    environment:
      << : *default-environment
    networks:
      - uplink
      - frontend
    ports:
      - 127.0.0.1:8000:8000

  client:
    image: ghcr.io/openslides/openslides/openslides-client:4.0.0-dev
    depends_on:
      - backend
      - autoupdate
      - auth
      - media
      - icc
    environment:
      << : *default-environment
    networks:
      - frontend

  backend:
    image: ghcr.io/openslides/openslides/openslides-backend:4.0.0-dev
    depends_on:
      - datastore-reader
      - datastore-writer
      - auth
      - postgres
    environment:
      << : *default-environment
    networks:
      - frontend
      - datastore-reader
      - datastore-writer
      - postgres
    secrets:
      - auth_token_key
      - auth_cookie_key

  datastore-reader:
    image: ghcr.io/openslides/openslides/openslides-datastore-reader:4.0.0-dev
    depends_on:
      - postgres
    environment:
      << : *default-environment
      NUM_WORKERS: 8
    networks:
      - datastore-reader
      - postgres

  datastore-writer:
    image: ghcr.io/openslides/openslides/openslides-datastore-writer:4.0.0-dev
    depends_on:
      - postgres
      - redis
    environment:
      << : *default-environment
    networks:
      - datastore-reader
      - datastore-writer
      - postgres
      - redis

  postgres:
    image: postgres:11
    environment:
      << : *default-environment
      POSTGRES_USER: openslides
      POSTGRES_PASSWORD: openslides
      POSTGRES_DB: openslides
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data

  autoupdate:
    image: ghcr.io/openslides/openslides/openslides-autoupdate:4.0.0-dev
    depends_on:
      - datastore-reader
      - redis
    environment:
      << : *default-environment
      MESSAGING: redis
      AUTH: ticket
    networks:
      - frontend
      - datastore-reader
      - redis
    secrets:
      - auth_token_key
      - auth_cookie_key

  auth:
    image: ghcr.io/openslides/openslides/openslides-auth:4.0.0-dev
    depends_on:
      - datastore-reader
      - redis
    environment:
      << : *default-environment
    networks:
      - frontend
      - datastore-reader
      - redis
    secrets:
      - auth_token_key
      - auth_cookie_key

  redis:
    image: redis:latest
    environment:
      << : *default-environment
    networks:
      - redis

  media:
    image: ghcr.io/openslides/openslides/openslides-media:4.0.0-dev
    depends_on:
      - backend
      - postgres
    environment:
      << : *default-environment
    networks:
      - frontend
      - datastore-reader
      - datastore-writer
      - postgres

  icc:
    image: ghcr.io/openslides/openslides/openslides-icc:4.0.0-dev
    depends_on:
      - datastore-reader
      - postgres
      - redis
    environment:
      << : *default-environment
      MESSAGING: redis
      AUTH: ticket
    networks:
      - frontend
      - datastore-reader
      - postgres
      - redis
    secrets:
      - auth_token_key
      - auth_cookie_key

  manage:
    image: ghcr.io/openslides/openslides/openslides-manage:4.0.0-dev
    depends_on:
      - datastore-reader
      - datastore-writer
      - auth
    environment:
      << : *default-environment
    networks:
      - uplink
      - frontend
      - datastore-reader
      - datastore-writer
      - postgres
      - redis
    secrets:
      - superadmin
    ports:
      - 127.0.0.1:9008:9008

networks:
  uplink:
  frontend:
    internal: true
  datastore-reader:
    internal: true
  datastore-writer:
    internal: true
  postgres:
    internal: true
  redis:
    internal: true

secrets:
  auth_token_key:
    file: ./secrets/auth_token_key
  auth_cookie_key:
    file: ./secrets/auth_cookie_key
  superadmin:
    file: ./secrets/superadmin
root@os4:~/openslides_08092021#
```

Thanks!

**Comment by ianhyzy** [comment]
I'm also having this issue on a new Ubuntu 20.04 vm:

```
root@openslides:/home/ian# docker-compose version
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

```
root@openslides:/home/ian# cat docker-compose.yml
---
x-default-environment: &default-environment
  ACTION_HOST: backend
  ACTION_PORT: 9002
  PRESENTER_HOST: backend
  PRESENTER_PORT: 9003

  DATASTORE_READER_HOST: datastore-reader
  DATASTORE_READER_PORT: 9010
  DATASTORE_WRITER_HOST: datastore-writer
  DATASTORE_WRITER_PORT: 9011
  DATASTORE_DATABASE_HOST: postgres
  DATASTORE_DATABASE_PORT: 5432
  DATASTORE_DATABASE_NAME: openslides
  DATASTORE_DATABASE_USER: openslides
  DATASTORE_DATABASE_PASSWORD: openslides

  AUTOUPDATE_HOST: autoupdate
  AUTOUPDATE_PORT: 9012

  AUTH_HOST: auth
  AUTH_PORT: 9004

  CACHE_HOST: redis
  CACHE_PORT: 6379

  MESSAGE_BUS_HOST: redis
  MESSAGE_BUS_PORT: 6379

  MEDIA_HOST: media
  MEDIA_PORT: 9006
  MEDIA_DATABASE_HOST: postgres
  MEDIA_DATABASE_NAME: openslides

  ICC_HOST: icc
  ICC_PORT: 9013
  ICC_REDIS_HOST: redis
  ICC_REDIS_PORT: 6379

  MANAGE_HOST: manage
  MANAGE_PORT: 9008

services:
  proxy:
    image: ghcr.io/openslides/openslides/openslides-proxy:4.0.0-dev
    depends_on:
      - client
      - backend
      - autoupdate
      - auth
      - media
      - icc
    environment:
      << : *default-environment
    networks:
      - uplink
      - frontend
    ports:
      - 127.0.0.1:8000:8000

  client:
    image: ghcr.io/openslides/openslides/openslides-client:4.0.0-dev
    depends_on:
      - backend
      - autoupdate
      - auth
      - media
      - icc
    environment:
      << : *default-environment
    networks:
      - frontend

  backend:
    image: ghcr.io/openslides/openslides/openslides-backend:4.0.0-dev
    depends_on:
      - datastore-reader
      - datastore-writer
      - auth
      - postgres
    environment:
      << : *default-environment
    networks:
      - frontend
      - datastore-reader
      - datastore-writer
      - postgres
    secrets:
      - auth_token_key
      - auth_cookie_key

  datastore-reader:
    image: ghcr.io/openslides/openslides/openslides-datastore-reader:4.0.0-dev
    depends_on:
      - postgres
    environment:
      << : *default-environment
      NUM_WORKERS: 8
    networks:
      - datastore-reader
      - postgres

  datastore-writer:
    image: ghcr.io/openslides/openslides/openslides-datastore-writer:4.0.0-dev
    depends_on:
      - postgres
      - redis
    environment:
      << : *default-environment
    networks:
      - datastore-reader
      - datastore-writer
      - postgres
      - redis

  postgres:
    image: postgres:11
    environment:
      << : *default-environment
      POSTGRES_USER: openslides
      POSTGRES_PASSWORD: openslides
      POSTGRES_DB: openslides
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data

  autoupdate:
    image: ghcr.io/openslides/openslides/openslides-autoupdate:4.0.0-dev
    depends_on:
      - datastore-reader
      - redis
    environment:
      << : *default-environment
      MESSAGING: redis
      AUTH: ticket
    networks:
      - frontend
      - datastore-reader
      - redis
    secrets:
      - auth_token_key
      - auth_cookie_key

  auth:
    image: ghcr.io/openslides/openslides/openslides-auth:4.0.0-dev
    depends_on:
      - datastore-reader
      - redis
    environment:
      << : *default-environment
    networks:
      - frontend
      - datastore-reader
      - redis
    secrets:
      - auth_token_key
      - auth_cookie_key

  redis:
    image: redis:latest
    environment:
      << : *default-environment
    networks:
      - redis

  media:
    image: ghcr.io/openslides/openslides/openslides-media:4.0.0-dev
    depends_on:
      - backend
      - postgres
    environment:
      << : *default-environment
    networks:
      - frontend
      - datastore-reader
      - datastore-writer
      - postgres

  icc:
    image: ghcr.io/openslides/openslides/openslides-icc:4.0.0-dev
    depends_on:
      - datastore-reader
      - postgres
      - redis
    environment:
      << : *default-environment
      MESSAGING: redis
      AUTH: ticket
    networks:
      - frontend
      - datastore-reader
      - postgres
      - redis
    secrets:
      - auth_token_key
      - auth_cookie_key

  manage:
    image: ghcr.io/openslides/openslides/openslides-manage:4.0.0-dev
    depends_on:
      - datastore-reader
      - datastore-writer
      - auth
    environment:
      << : *default-environment
    networks:
      - uplink
      - frontend
      - datastore-reader
      - datastore-writer
      - postgres
      - redis
    secrets:
      - superadmin
    ports:
      - 127.0.0.1:9008:9008

networks:
  uplink:
  frontend:
    internal: true
  datastore-reader:
    internal: true
  datastore-writer:
    internal: true
  postgres:
    internal: true
  redis:
    internal: true

secrets:
  auth_token_key:
    file: ./secrets/auth_token_key
  auth_cookie_key:
    file: ./secrets/auth_cookie_key
  superadmin:
    file: ./secrets/superadmin
```
